.TH CRAZYLIB 6 2013-09-10
.SH NAME
CrazyLib \- Play mad-libs, a phrasal template word game.
.SH SYNOPSIS
.B CrazyLib
[filename]
.SH DESCRIPTION
.B CrazyLib
prompts for words or phrases to substitute for blanks in a story.
The story is then displayed and can be saved.
.SH NOTES
You can create your own madlibs by putting them into a text file with the blanks
designated within <angle brackets>. To have a single input be put in multiple
places, use an id tag within the brackets as so: <example#1>.
What follows the # is expected to be a unique number regardless of what
precedes it. So, <this#1> will be replaced with the same word as <that#1>.
